# Generated by Django 4.2.7 on 2023-11-15 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_rename_original_bag_order_original_cart_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='original_cart',
            new_name='original_bag',
        ),
    ]
