# Generated by Django 4.2.7 on 2023-11-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.SlugField(blank=True, max_length=254, null=True),
        ),
    ]
