# Generated by Django 4.2.7 on 2023-11-14 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_brand_remove_product_model_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='weight',
            new_name='brand',
        ),
    ]
